# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, unique=True)),
                ('hex', models.CharField(max_length=7, unique=True)),
            ],
        ),
    ]
