# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('hexadecimal', models.CharField(max_length=7, unique=True)),
                ('red', models.PositiveSmallIntegerField()),
                ('green', models.PositiveSmallIntegerField()),
                ('blue', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Colors',
        ),
    ]
