# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160507_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='descripcion',
            field=models.CharField(blank=True, max_length=140, unique=True),
        ),
    ]
